### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by rob-uk-hub** [mikes222/mapsforge_flutter#106]
Hi,

When I try to run the unit tests many of them fail.  I have tried on MacOS and Windows, are there any setup instructions available for the tests?

An example failure:

```
The following assertion was thrown while running async test code:
Golden "splittedlabel.png": Pixel test failed, 94.20%, 452145px diff detected.
Failure feedback can be found at
/Users/rob/git/mapsforge_flutter/mapsforge_flutter/test/mapfile/failures

When the exception was thrown, this was the stack:
#0      LocalFileComparator.compare (package:flutter_test/src/_goldens_io.dart:106:5)
<asynchronous suspension>
#1      MatchesGoldenFile.matchAsync.<anonymous closure> (package:flutter_test/src/_matchers_io.dart:118:32)
<asynchronous suspension>
<asynchronous suspension>
#3      _expect.<anonymous closure> (package:matcher/src/expect/expect.dart:123:26)
<asynchronous suspension>
<asynchronous suspension>
#5      expectLater.<anonymous closure> (package:flutter_test/src/widget_tester.dart:512:24)
<asynchronous suspension>
#6      TestHelper.pumpWidget (file:///Users/rob/git/mapsforge_flutter/mapsforge_flutter/test/testhelper.dart:29:5)
<asynchronous suspension>
#7      main.<anonymous closure> (file:///Users/rob/git/mapsforge_flutter/mapsforge_flutter/test/mapfile/label_test.dart:99:5)
<asynchronous suspension>
#8      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:183:15)
<asynchronous suspension>
#9      TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1017:5)
<asynchronous suspension>
<asynchronous suspension>
```

Thanks,

**Comment by mikes222** [comment]
The implementation of flutter graphics differs from version to version. Therefore it is not easy to do a pixel-perfect comparison. I will rerun all tests and update the masterfiles with the newest images in the next days. Hope this also solves your problems. 

In case of errors the golden library creates difference-files in a subfolder ``failures``. You can easily view them and see the differences.
